// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgC8bnsb56HsmXlhX9qNmROFnwmLlK9ZQ',
    appId: '1:162756144812:web:b1c08273b883d818fef909',
    messagingSenderId: '162756144812',
    projectId: 'todo-app-f6323',
    authDomain: 'todo-app-f6323.firebaseapp.com',
    storageBucket: 'todo-app-f6323.appspot.com',
    measurementId: 'G-T1EFHD98T7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGZUuQRnKXUkKeDwZ8RHYiRn27IfPZXsA',
    appId: '1:162756144812:android:706862ef89714415fef909',
    messagingSenderId: '162756144812',
    projectId: 'todo-app-f6323',
    storageBucket: 'todo-app-f6323.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtzXUbM661a2EJAWTN1rlqx7f4-wH8Ir4',
    appId: '1:162756144812:ios:84cb671db35e6e28fef909',
    messagingSenderId: '162756144812',
    projectId: 'todo-app-f6323',
    storageBucket: 'todo-app-f6323.appspot.com',
    iosBundleId: 'com.example.toder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtzXUbM661a2EJAWTN1rlqx7f4-wH8Ir4',
    appId: '1:162756144812:ios:f979226984040255fef909',
    messagingSenderId: '162756144812',
    projectId: 'todo-app-f6323',
    storageBucket: 'todo-app-f6323.appspot.com',
    iosBundleId: 'com.example.toder.RunnerTests',
  );
}
